### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by lee-to-the-moon** [youribonnaffe/ftp-reverse-proxy#4]
I wish the author could be more clear

**Comment by youribonnaffe** [comment]
Do you have any specific question/issue in mind?

The README provides a few instruction and binaries can be downloaded from https://github.com/youribonnaffe/ftp-reverse-proxy/releases/tag/v0.1.

**Comment by lee-to-the-moon** [comment]
> Do you have any specific question/issue in mind?
> 
> The README provides a few instruction and binaries can be downloaded from https://github.com/youribonnaffe/ftp-reverse-proxy/releases/tag/v0.1.

I want to know how to use it？thanks.

**Comment by youribonnaffe** [comment]
Like this ? 
```
./ftp-reverse-proxy -port 8080 -target ftp://user:pwd@host:port
```
